// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfG_FlUpOumfs6zWLZ39E-JSct5j_T87U',
    appId: '1:123482540296:web:3c409d53d994382efe84bd',
    messagingSenderId: '123482540296',
    projectId: 'career-caoching',
    authDomain: 'career-caoching.firebaseapp.com',
    storageBucket: 'career-caoching.firebasestorage.app',
    measurementId: 'G-GZBYXXSQ43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN8fEUfl7tTFvE3yyQ8YHveR7i0faaLPg',
    appId: '1:123482540296:android:af27fa1b17454cd1fe84bd',
    messagingSenderId: '123482540296',
    projectId: 'career-caoching',
    storageBucket: 'career-caoching.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiGNI2Nt4xx0EU2Iyb6I8v3cKZkHbLXY4',
    appId: '1:123482540296:ios:5b2a1987b255a514fe84bd',
    messagingSenderId: '123482540296',
    projectId: 'career-caoching',
    storageBucket: 'career-caoching.firebasestorage.app',
    iosBundleId: 'com.example.careerCoaching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiGNI2Nt4xx0EU2Iyb6I8v3cKZkHbLXY4',
    appId: '1:123482540296:ios:5b2a1987b255a514fe84bd',
    messagingSenderId: '123482540296',
    projectId: 'career-caoching',
    storageBucket: 'career-caoching.firebasestorage.app',
    iosBundleId: 'com.example.careerCoaching',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfG_FlUpOumfs6zWLZ39E-JSct5j_T87U',
    appId: '1:123482540296:web:80427d9f0df50156fe84bd',
    messagingSenderId: '123482540296',
    projectId: 'career-caoching',
    authDomain: 'career-caoching.firebaseapp.com',
    storageBucket: 'career-caoching.firebasestorage.app',
    measurementId: 'G-9WHDY99L85',
  );
}
